'use strict';

require('dotenv').config();

const express   = require('express');
const multer    = require('multer');
const helmet    = require('helmet');
const rateLimit = require('express-rate-limit');
const session   = require('express-session');
const crypto    = require('crypto');
const path      = require('path');
const { execSync } = require('child_process');

// Resolve git hash once at startup
let GIT_HASH = 'unknown';
try { GIT_HASH = execSync('git rev-parse --short HEAD', { timeout: 2000 }).toString().trim(); } catch {}

// Node 18+ required for built-in fetch
if (parseInt(process.versions.node, 10) < 18) {
  console.error('Node.js >= 18 is required (built-in fetch). Please upgrade.');
  process.exit(1);
}

const app  = express();
const PORT = parseInt(process.env.PORT, 10) || 3000;

// Trust first proxy (nginx) so rate limiting uses real client IPs
// and secure cookies work behind HTTPS termination
if (process.env.NODE_ENV === 'production') app.set('trust proxy', 1);

// ─── Config ──────────────────────────────────────────────────────────────────
const DISCORD = {
  clientId:     process.env.DISCORD_CLIENT_ID,
  clientSecret: process.env.DISCORD_CLIENT_SECRET,
  redirectUri:  process.env.DISCORD_REDIRECT_URI,
  guildId:      process.env.DISCORD_GUILD_ID,
  requiredRole: process.env.DISCORD_REQUIRED_ROLE_ID,
};

const SESSION_SECRET = process.env.SESSION_SECRET
  || crypto.randomBytes(32).toString('hex');

//
// TTL design:
//   PENDING_TTL_MS  24 h  — user has a full working day for staff to be available
//   CLAIMED_TTL_MS  15 m  — once staff opens the document, 15 min to review;
//                           prevents stale "open tab" sessions holding data
//   REVIEWED_TTL_MS  1 h  — short window so user can confirm their hash was seen
//
const PENDING_TTL_MS  = 24 * 60 * 60 * 1000;
const CLAIMED_TTL_MS  = 15 * 60 * 1000;
const REVIEWED_TTL_MS =  1 * 60 * 60 * 1000;
const MAX_FILE_SIZE   = 10 * 1024 * 1024;
const MAX_PENDING     = 500; // hard ceiling on in-memory documents; prevents RAM exhaustion under distributed upload flood

const ALLOWED_MIME = new Set(['image/jpeg', 'image/png']);

// Submission ID format: UUID v4 (crypto.randomUUID) — 122 bits of entropy.
// Staff can only access a document if they know the exact UUID, are authenticated
// via Discord, and the document hasn't expired or been claimed by someone else.
const HASH_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;

// ─── In-Memory Stores ────────────────────────────────────────────────────────
// NOTE: Node.js GC may create internal Buffer copies before our fill(0) runs.
// This is an inherent limitation of managed runtimes. RAM storage is still
// vastly safer than disk — no persistence, no filesystem forensics, no
// accidental backups. For hardened deployments, disable OS core dumps and
// restrict swap to prevent memory being paged to disk.
//
// pendingStore:  hash → { imageBuffer, mimeType, uploadedAt, expiresAt }
// claimedStore:  hash → { imageBuffer, mimeType, claimedAt, expiresAt, staffId }
// reviewedStore: hash → { reviewedAt, expiresAt }
const pendingStore  = new Map();
const claimedStore  = new Map();
const reviewedStore = new Map();

// ─── Helpers ─────────────────────────────────────────────────────────────────
function generateHash() {
  // UUID v4 — 122 bits of entropy, generated by the Node.js built-in
  return crypto.randomUUID();
}

function wipeBuffer(entry) {
  if (entry?.imageBuffer && Buffer.isBuffer(entry.imageBuffer)) {
    entry.imageBuffer.fill(0);
  }
}

// Magic-byte allowlist — validates actual file content, not just the MIME header
// sent by the client. Prevents mislabelled or polyglot uploads from entering RAM.
const MAGIC_BYTES = {
  'image/jpeg': [0xFF, 0xD8, 0xFF],
  'image/png':  [0x89, 0x50, 0x4E, 0x47],
};
function validateMagicBytes(buffer, mimeType) {
  const expected = MAGIC_BYTES[mimeType];
  if (!expected || buffer.length < expected.length) return false;
  for (let i = 0; i < expected.length; i++) {
    if (buffer[i] !== expected[i]) return false;
  }
  return true;
}

function discordConfigured() {
  return DISCORD.clientId && DISCORD.clientSecret && DISCORD.redirectUri
      && DISCORD.guildId  && DISCORD.requiredRole;
}

// ─── Periodic Cleanup ────────────────────────────────────────────────────────
setInterval(() => {
  const now = Date.now();
  for (const [h, e] of pendingStore)  { if (e.expiresAt < now) { wipeBuffer(e); pendingStore.delete(h); } }
  for (const [h, e] of claimedStore)  { if (e.expiresAt < now) { wipeBuffer(e); claimedStore.delete(h); } }
  for (const [h, e] of reviewedStore) { if (e.expiresAt < now) { reviewedStore.delete(h); } }
}, 60_000).unref(); // .unref() allows clean SIGTERM/SIGINT shutdown without waiting for next tick

// ─── Security Middleware ─────────────────────────────────────────────────────
app.use(helmet({
  contentSecurityPolicy: {
    directives: {
      defaultSrc: ["'self'"],
      imgSrc:     ["'self'"],
      scriptSrc:  ["'self'"],
      styleSrc:   ["'self'"],
      objectSrc:  ["'none'"],
      frameSrc:   ["'none'"],
      connectSrc: ["'self'"],
    },
  },
  crossOriginEmbedderPolicy: true,
}));

app.use(express.json({ limit: '4kb' }));
app.use(express.static(path.join(__dirname, 'public')));

// Clean URL for the staff portal — /staff serves staff.html
app.get('/staff', (_, res) => res.sendFile(path.join(__dirname, 'public', 'staff.html')));

// ─── Session ─────────────────────────────────────────────────────────────────
// sameSite: 'lax' (not 'strict') is required — Discord OAuth redirect back to
// our callback URL is a cross-site top-level GET and 'strict' would drop the
// cookie, breaking the OAuth state check.
app.use(session({
  secret:            SESSION_SECRET,
  resave:            false,
  saveUninitialized: false,
  name:              'sid',
  cookie: {
    httpOnly: true,
    secure:   process.env.NODE_ENV === 'production',
    sameSite: 'lax',
    maxAge:   8 * 60 * 60 * 1000, // 8-hour staff session
  },
}));

// ─── Rate Limiters ───────────────────────────────────────────────────────────
const mkLimiter = (windowMs, max, message) =>
  rateLimit({ windowMs, max, message: { error: message }, standardHeaders: true, legacyHeaders: false });

const uploadLimiter = mkLimiter(15 * 60_000, 5,  'Too many uploads. Please try again later.');
const statusLimiter = mkLimiter( 5 * 60_000, 40, 'Too many status checks. Please slow down.');
const staffLimiter  = mkLimiter( 5 * 60_000, 20, 'Too many requests. Please try again later.');
const authLimiter   = mkLimiter(15 * 60_000, 25, 'Too many auth attempts. Please try again later.');

// ─── Multer — RAM only, zero disk writes ─────────────────────────────────────
const upload = multer({
  storage: multer.memoryStorage(),
  limits:  { fileSize: MAX_FILE_SIZE, files: 1 },
  fileFilter(_, file, cb) {
    ALLOWED_MIME.has(file.mimetype)
      ? cb(null, true)
      : cb(Object.assign(new Error('INVALID_TYPE'), { status: 415 }));
  },
});

// ─── Auth Guard ──────────────────────────────────────────────────────────────
function requireStaff(req, res, next) {
  if (req.session?.isStaff === true) return next();
  res.status(401).json({ error: 'Unauthorised. Please sign in via Discord.', code: 'UNAUTHENTICATED' });
}

// ─── Discord OAuth ────────────────────────────────────────────────────────────
// Scopes used:
//   identify           — get user's id, username, avatar
//   guilds.members.read — get member object (incl. roles) for a specific guild
//                         without needing the user to share all their guilds

// GET /auth/discord  — start the OAuth flow
app.get('/auth/discord', authLimiter, (req, res) => {
  if (!discordConfigured()) return res.redirect('/staff?error=not_configured');

  const state = crypto.randomBytes(16).toString('hex');
  req.session.oauthState = state;

  const params = new URLSearchParams({
    client_id:     DISCORD.clientId,
    redirect_uri:  DISCORD.redirectUri,
    response_type: 'code',
    scope:         'identify guilds.members.read',
    state,
  });

  res.redirect(`https://discord.com/oauth2/authorize?${params}`);
});

// GET /auth/discord/callback  — Discord redirects here after user authorises
app.get('/auth/discord/callback', authLimiter, async (req, res) => {
  const { code, state, error } = req.query;

  if (error) return res.redirect(`/staff?error=${encodeURIComponent(String(error).slice(0, 64))}`);

  // CSRF check — delete state first (prevents reuse on retry), then validate
  const expectedState = req.session.oauthState;
  delete req.session.oauthState;
  if (!state || state !== expectedState) {
    return res.redirect('/staff?error=invalid_state');
  }

  if (!code || typeof code !== 'string' || code.length > 256) {
    return res.redirect('/staff?error=invalid_code');
  }

  try {
    // 5-second timeout on all Discord API calls (AbortSignal.timeout requires Node 18+)
    const timeout = () => AbortSignal.timeout(5000);

    // 1. Exchange code for access token
    const tokenRes = await fetch('https://discord.com/api/oauth2/token', {
      method:  'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body:    new URLSearchParams({
        client_id:     DISCORD.clientId,
        client_secret: DISCORD.clientSecret,
        grant_type:    'authorization_code',
        code,
        redirect_uri:  DISCORD.redirectUri,
      }),
      signal: timeout(),
    });
    if (!tokenRes.ok) return res.redirect('/staff?error=token_failed');

    const { access_token } = await tokenRes.json();
    if (!access_token) return res.redirect('/staff?error=token_missing');

    const authHeader = { Authorization: `Bearer ${access_token}` };
    // Helper: revoke Discord token — fire-and-forget, never awaited
    const revokeToken = () => fetch('https://discord.com/api/oauth2/token/revoke', {
      method:  'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body:    new URLSearchParams({
        client_id:     DISCORD.clientId,
        client_secret: DISCORD.clientSecret,
        token:         access_token,
      }),
      signal: AbortSignal.timeout(5000),
    }).catch(() => {});

    // 2. Get user identity
    const userRes = await fetch('https://discord.com/api/users/@me', { headers: authHeader, signal: timeout() });
    if (!userRes.ok) { revokeToken(); return res.redirect('/staff?error=user_fetch_failed'); }
    const user = await userRes.json();

    // 3. Check guild membership + role
    const memberRes = await fetch(
      `https://discord.com/api/users/@me/guilds/${encodeURIComponent(DISCORD.guildId)}/member`,
      { headers: authHeader, signal: timeout() }
    );

    if (memberRes.status === 404) { revokeToken(); return res.redirect('/staff?error=not_in_guild'); }
    if (!memberRes.ok)            { revokeToken(); return res.redirect('/staff?error=member_fetch_failed'); }

    const member = await memberRes.json();

    if (!Array.isArray(member.roles) || !member.roles.includes(DISCORD.requiredRole)) {
      revokeToken();
      return res.redirect('/staff?error=missing_role');
    }

    // 4. Revoke token immediately — we have everything we need, no reason to keep it alive
    revokeToken();

    // 5. Sanitise values from Discord API before storing in session
    const SNOWFLAKE_RE = /^\d{15,21}$/;
    const AVATAR_RE    = /^[0-9a-f]{32}$/;
    const safeId       = SNOWFLAKE_RE.test(user.id ?? '')     ? user.id      : null;
    const safeAvatar   = AVATAR_RE.test(user.avatar ?? '')    ? user.avatar  : null;
    const safeUsername = String(user.global_name || user.username || 'Unknown').slice(0, 64);

    // All checks passed — create an authenticated session
    req.session.regenerate((err) => {
      if (err) return res.redirect('/staff?error=session_error');
      req.session.isStaff = true;
      req.session.discord = {
        id:       safeId,
        username: safeUsername,
        avatar:   safeAvatar,
      };
      res.redirect('/staff');
    });

  } catch (e) {
    console.error('[Discord OAuth]', e.message);
    res.redirect('/staff?error=internal_error');
  }
});

// POST /auth/discord/logout
app.post('/auth/discord/logout', requireStaff, (req, res) => {
  req.session.destroy((err) => {
    if (err) console.error('[logout] session.destroy failed:', err.message);
    // Clear the cookie regardless — even if server-side destroy failed,
    // removing the cookie prevents the client from sending it again.
    // The session will expire naturally via maxAge.
    res.clearCookie('sid');
    res.json({ success: true });
  });
});

// ─── User Routes ─────────────────────────────────────────────────────────────

// POST /api/upload
// Stores image in RAM only, returns a short verification hash for the user
// to share with a staff member. The hash expires after 24 hours.
app.post('/api/upload', uploadLimiter, upload.single('idImage'), (req, res) => {
  if (!req.file) return res.status(400).json({ error: 'No file received.' });

  // Validate actual file magic bytes — guards against MIME spoofing via Content-Type header
  if (!validateMagicBytes(req.file.buffer, req.file.mimetype)) {
    req.file.buffer.fill(0);
    return res.status(415).json({ error: 'File content does not match the declared type. Only JPEG and PNG are accepted.' });
  }

  // Collision-safe hash generation (probability of collision is negligible
  // with 2^32 space and at most a few hundred active submissions at any time)
  let hash;
  let attempts = 0;
  do {
    hash = generateHash();
    attempts++;
  } while (
    (pendingStore.has(hash) || claimedStore.has(hash) || reviewedStore.has(hash))
    && attempts < 20
  );

  if (attempts >= 20) {
    wipeBuffer({ imageBuffer: req.file.buffer });
    return res.status(503).json({ error: 'Service temporarily unavailable. Please retry.' });
  }

  if (pendingStore.size >= MAX_PENDING) {
    wipeBuffer({ imageBuffer: req.file.buffer });
    return res.status(503).json({ error: 'Service is currently at capacity. Please try again later.' });
  }

  const now = Date.now();
  pendingStore.set(hash, {
    imageBuffer: req.file.buffer,
    mimeType:    req.file.mimetype,
    uploadedAt:  now,
    expiresAt:   now + PENDING_TTL_MS,
  });

  res.status(201).json({
    hash,
    expiresAt:      now + PENDING_TTL_MS,
    expiresInHours: PENDING_TTL_MS / 3_600_000,
  });
});

// GET /api/status/:hash
// User polls this to see if their document has been reviewed.
// Returns one of: pending | reviewing | reviewed | not_found
app.get('/api/status/:hash', statusLimiter, (req, res) => {
  const hash = (req.params.hash ?? '').toLowerCase().trim();
  if (!HASH_RE.test(hash)) return res.status(400).json({ error: 'Invalid UUID format.' });

  if (pendingStore.has(hash)) {
    const e = pendingStore.get(hash);
    return res.json({ status: 'pending', expiresAt: e.expiresAt });
  }
  if (claimedStore.has(hash)) {
    return res.json({ status: 'reviewing' });
  }
  if (reviewedStore.has(hash)) {
    const e = reviewedStore.get(hash);
    return res.json({ status: 'reviewed', reviewedAt: e.reviewedAt });
  }

  res.status(404).json({ status: 'not_found' });
});

// ─── Staff Routes ─────────────────────────────────────────────────────────────

// GET /api/staff/me  — used by the frontend to check auth state
app.get('/api/staff/me', requireStaff, staffLimiter, (req, res) => {
  res.json({ user: req.session.discord });
});

// GET /api/staff/avatar  — proxies the Discord CDN avatar through the server.
// Keeps all image loads same-origin (satisfies imgSrc: 'self' CSP and COEP).
// Validates snowflake ID and avatar hash format to prevent SSRF.
app.get('/api/staff/avatar', requireStaff, staffLimiter, async (req, res) => {
  const { id, avatar } = req.session.discord || {};
  if (!id || !avatar) return res.status(404).end();

  // Discord snowflake: 15-21 digit integer; avatar hash: 32 hex chars
  if (!/^\d{15,21}$/.test(id) || !/^[0-9a-f]{32}$/.test(avatar)) {
    return res.status(400).end();
  }

  try {
    const cdnRes = await fetch(`https://cdn.discordapp.com/avatars/${id}/${avatar}.png?size=40`, {
      signal: AbortSignal.timeout(5000),
    });
    if (!cdnRes.ok) return res.status(404).end();
    const buf = Buffer.from(await cdnRes.arrayBuffer());
    // Verify the CDN response is actually a PNG before serving
    const PNG_MAGIC = [0x89, 0x50, 0x4E, 0x47];
    if (buf.length < 4 || PNG_MAGIC.some((b, i) => buf[i] !== b)) {
      return res.status(502).end();
    }
    res.set({
      'Content-Type':           'image/png',
      'Cache-Control':          'private, max-age=3600',
      'X-Content-Type-Options': 'nosniff',
    });
    res.send(buf);
  } catch {
    res.status(502).end();
  }
});

// GET /api/build  — exposes build metadata to the frontend footer
app.get('/api/build', rateLimit({ windowMs: 60_000, max: 30, standardHeaders: true, legacyHeaders: false }), (_, res) => {
  res.json({ year: new Date().getFullYear(), gitHash: GIT_HASH });
});

// POST /api/staff/lookup
// Staff inputs a hash to claim a document. On success the document moves from
// pendingStore → claimedStore and a 15-minute viewing window begins.
// Only the staff member who claimed it can then fetch the image or mark it done.
app.post('/api/staff/lookup', requireStaff, staffLimiter, (req, res) => {
  const hash = (req.body?.hash ?? '').toLowerCase().trim();
  if (!HASH_RE.test(hash)) {
    return res.status(400).json({ error: 'Invalid UUID format.' });
  }

  if (claimedStore.has(hash)) {
    return res.status(409).json({
      error: 'This document is currently being reviewed by another staff session.',
      code:  'ALREADY_CLAIMED',
    });
  }
  if (reviewedStore.has(hash)) {
    return res.status(410).json({
      error: 'This document has already been reviewed and permanently destroyed.',
      code:  'ALREADY_REVIEWED',
    });
  }

  const entry = pendingStore.get(hash);
  if (!entry) {
    return res.status(404).json({
      error: 'Hash not found. It may have expired (24 h limit) or been entered incorrectly.',
      code:  'NOT_FOUND',
    });
  }

  const now = Date.now();
  claimedStore.set(hash, {
    imageBuffer:    entry.imageBuffer,
    mimeType:       entry.mimeType,
    claimedAt:      now,
    expiresAt:      now + CLAIMED_TTL_MS,
    staffId:        req.session.discord?.id,
  });
  pendingStore.delete(hash);

  res.json({
    success:          true,
    mimeType:         entry.mimeType,
    viewExpiresAt:    now + CLAIMED_TTL_MS,
    expiresInMinutes: CLAIMED_TTL_MS / 60_000,
  });
});

// GET /api/staff/image/:hash
// Serves the raw image buffer. Only the staff member who claimed it can fetch it.
// Cache headers ensure the browser never caches this response.
app.get('/api/staff/image/:hash', requireStaff, staffLimiter, (req, res) => {
  const hash = (req.params.hash ?? '').toLowerCase().trim();
  if (!HASH_RE.test(hash)) return res.status(400).json({ error: 'Invalid UUID format.' });

  const entry = claimedStore.get(hash);
  if (!entry) return res.status(404).json({ error: 'Document not found or the 15-minute viewing window has expired.' });

  if (entry.staffId === null || entry.staffId !== req.session.discord?.id) {
    return res.status(403).json({ error: 'This document was claimed by a different staff session.' });
  }

  res.set({
    'Content-Type':           entry.mimeType,
    'Content-Disposition':    'inline',
    'Cache-Control':          'no-store, no-cache, must-revalidate',
    'Pragma':                 'no-cache',
    'X-Content-Type-Options': 'nosniff',
  });
  res.send(entry.imageBuffer);
});

// POST /api/staff/done/:hash
// Staff marks the document as reviewed. Buffer is zeroed immediately and the
// document is removed from memory — this action cannot be undone.
app.post('/api/staff/done/:hash', requireStaff, staffLimiter, (req, res) => {
  const hash = (req.params.hash ?? '').toLowerCase().trim();
  if (!HASH_RE.test(hash)) return res.status(400).json({ error: 'Invalid UUID format.' });

  const entry = claimedStore.get(hash);
  if (!entry) {
    return res.status(404).json({ error: 'Document not found or already processed.' });
  }
  if (entry.staffId === null || entry.staffId !== req.session.discord?.id) {
    return res.status(403).json({ error: 'Only the staff member who claimed this document can finalise it.' });
  }

  wipeBuffer(entry);
  claimedStore.delete(hash);

  const now = Date.now();
  reviewedStore.set(hash, {
    reviewedAt: now,
    expiresAt:  now + REVIEWED_TTL_MS,
  });

  res.json({ success: true });
});

// ─── Error Handler ───────────────────────────────────────────────────────────
// eslint-disable-next-line no-unused-vars
app.use((err, _req, res, _next) => {
  if (err.code === 'LIMIT_FILE_SIZE') {
    return res.status(413).json({ error: `File too large. Maximum is ${MAX_FILE_SIZE / 1_048_576} MB.` });
  }
  if (err.status === 415) {
    return res.status(415).json({ error: 'Unsupported file type. Only JPEG and PNG are accepted.' });
  }
  console.error('[ERROR]', err.message);
  res.status(500).json({ error: 'Internal server error.' });
});

// ─── Start ───────────────────────────────────────────────────────────────────
app.listen(PORT, () => {
  console.log(`\n  Secure ID Verification Platform`);
  console.log(`  http://localhost:${PORT}\n`);
  if (!discordConfigured()) {
    console.warn('  [WARN] Discord OAuth is not fully configured — see .env.example');
  }
  if (!process.env.SESSION_SECRET) {
    console.warn('  [WARN] SESSION_SECRET not set — sessions reset on every restart');
    console.warn('         Run:  npm run secret\n');
  }
});
